- name: Check vCenter
  hosts: localhost
  vars:
    datastore: "{{ lookup('env', 'GOVC_DATASTORE') }}"

  collections:
  - vmware.vmware_rest
  tasks:
  - name: "datacenters"
    vcenter_datacenter_info:
    register: my_datacenters
  - debug: msg="{{ my_datacenters }}"
  - name: "clusters"
    vcenter_cluster_info:
    register: my_cluster
  - debug: msg="{{ my_cluster }}"
  - name: "datastores"
    vcenter_datastore_info:
      filter_names:
      - "{{ datastore }}"
    register: my_datastores
  - debug: msg="{{ my_datastores }}"
